# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OBJC-Camera-Version' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  pod 'OCMock', '~> 3.4'
  pod 'iCarousel', '~> 1.8'
  pod 'ReactiveObjC'
  pod 'Toast', '~> 4.0'
  target 'OBJC-Camera-VersionTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'OBJC-Camera-VersionUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end
